version: '3.1'

services:
    db:
        image: mysql:5.7.37
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        depends_on:
            - db
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
    nginx:
        build: nginx
        ports:
            - 83:80
        depends_on:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
